sudo: false
language: go
os:
  - linux
  - osx
go:
  - tip
go_import_path: github.com/flosch/pongo2-addons/v4
install:
  - go mod tidy
script:
  - go test -v -covermode=count -coverprofile=coverage.out
